### ISSUE TITLE
Handle only exceptions?

### ISSUE THREAD

**Issue by PurpleVsGreen** [bkrukowski/error-dumper#2]
Handling errors causes silenced errors to throw exceptions, which is not useful when dealing with foreign code.

Is there a mode in which only exceptions are caught?

**Comment by bkrukowski** [comment]
I'll think about this, If you need, you can fork this repository and comment lines 41-42 in class `\ErrorDumper\Handlers\RegisterErrorHandler`

**Comment by PurpleVsGreen** [comment]
Thanks, now I can enable error_reporting again :)

**Comment by bkrukowski** [comment]
Already you can set kind of catching errors:
https://github.com/bkrukowski/error-dumper/blob/master/readme.md#handle-only-exceptions

**Comment by bkrukowski** [comment]
@PurpleVsGreen I hope it will be useful for use - [awesomite/error-dumper](https://github.com/awesomite/error-dumper).
Code is written, there are new features, for example you can serialize exception (to preview it later) using `ClonedException` class, usually you cannot serialize exceptions - [example](http://ideone.com/kG9TLL).
